Array methods: 117(Ruby 3.3)
--------------------
[:[], :new, :try_convert, :allocate, :attached_object, :superclass, :subclasses, :<=>, :autoload, :<=, :>=, :==, :===, :autoload?, :included_modules, :include?,
 :set_temporary_name, :ancestors, :attr, :attr_reader, :attr_writer, :attr_accessor, :define_method, :instance_methods, :public_instance_methods, :protected_instance_methods,
 :private_instance_methods, :undefined_instance_methods, :freeze, :inspect, :const_get, :constants, :const_missing, :const_defined?, :const_set, :const_source_location,
 :remove_class_variable, :class_variable_get, :<, :class_variables, :>, :private_constant, :class_variable_set, :class_variable_defined?, :public_constant, :include,
 :deprecate_constant, :singleton_class?, :prepend, :refinements, :instance_method, :to_s, :module_exec, :class_exec, :module_eval, :class_eval, :pretty_print, :name,
 :remove_method, :undef_method, :alias_method, :method_defined?, :public_method_defined?, :private_method_defined?, :protected_method_defined?, :public_class_method,
 :private_class_method, :public_instance_method, :pretty_print_cycle, :pretty_print_inspect, :pretty_print_instance_variables, :singleton_class, :dup, :itself,
 :methods, :singleton_methods, :protected_methods, :private_methods, :public_methods, :instance_variables, :instance_variable_get, :instance_variable_set, :instance_variable_defined?,
 :remove_instance_variable, :instance_of?, :kind_of?, :is_a?, :display, :public_send, :pretty_inspect, :extend, :clone, :!~, :frozen?, :class, :then, :tap, :nil?,
 :eql?, :respond_to?, :method, :public_method, :singleton_method, :define_singleton_method, :yield_self, :hash, :object_id, :send, :to_enum, :enum_for, :equal?,
 :!, :__send__, :!=, :instance_eval, :instance_exec, :__id__]

Hash methods: 119(Ruby 3.3)
---------------------
[:ruby2_keywords_hash?, :[], :try_convert, :ruby2_keywords_hash, :allocate, :attached_object, :superclass, :subclasses, :new, :<=>, :autoload, :<=, :>=, :==, :===,
 :autoload?, :included_modules, :include?, :set_temporary_name, :ancestors, :attr, :attr_reader, :attr_writer, :attr_accessor, :define_method, :instance_methods,
 :public_instance_methods, :protected_instance_methods, :private_instance_methods, :undefined_instance_methods, :freeze, :inspect, :const_get, :constants,
 :const_missing, :const_defined?, :const_set, :const_source_location, :remove_class_variable, :class_variable_get, :<, :class_variables, :>, :private_constant,
 :class_variable_set, :class_variable_defined?, :public_constant, :include, :deprecate_constant, :singleton_class?, :prepend, :refinements, :instance_method, :to_s,
 :module_exec, :class_exec, :module_eval, :class_eval, :pretty_print, :name, :remove_method, :undef_method, :alias_method, :method_defined?, :public_method_defined?,
 :private_method_defined?, :protected_method_defined?, :public_class_method, :private_class_method, :public_instance_method, :pretty_print_cycle, :pretty_print_inspect,
 :pretty_print_instance_variables, :singleton_class, :dup, :itself, :methods, :singleton_methods, :protected_methods, :private_methods, :public_methods, :instance_variables,
 :instance_variable_get, :instance_variable_set, :instance_variable_defined?, :remove_instance_variable, :instance_of?, :kind_of?, :is_a?, :display, :public_send, :pretty_inspect,
 :extend, :clone, :!~, :frozen?, :class, :then, :tap, :nil?, :eql?, :respond_to?, :method, :public_method, :singleton_method, :define_singleton_method, :yield_self,
 :hash, :object_id, :send, :to_enum, :enum_for, :equal?, :!, :__send__, :!=, :instance_eval, :instance_exec, :__id__]

Model methods: 681
--------------------
:_validate_callbacks, :my_import, :_validators, :defined_enums, :attribute_type_decorations, :establish_connection, 
:nested_attributes_options, :nested_attributes_options=, :primary_key_prefix_type=, :table_name_prefix?, :table_name_suffix?, 
:schema_migrations_table_name?, :internal_metadata_table_name?, :protected_environments?, :store_full_sti_class, 
:store_full_sti_class=, :pluralize_table_names, :store_full_sti_class?, :default_scopes, :table_name_suffix, 
:default_scope_override, :default_scopes=, :nested_attributes_options?, :schema_migrations_table_name, :default_scope_override=, 
:_rollback_callbacks, :_commit_callbacks, :_before_commit_callbacks, :cache_timestamp_format=, :_commit_callbacks?,
 :cache_timestamp_format?, :_commit_callbacks=, :_rollback_callbacks?, :_rollback_callbacks=, :_before_commit_callbacks=, 
:_before_commit_without_transaction_enrollment_callbacks, :_before_commit_without_transaction_enrollment_callbacks?, 
:_before_commit_without_transaction_enrollment_callbacks=, :_validators=, :_commit_without_transaction_enrollment_callbacks?, 
:_commit_without_transaction_enrollment_callbacks=, :_rollback_without_transaction_enrollment_callbacks, 
:_rollback_without_transaction_enrollment_callbacks?, :_commit_without_transaction_enrollment_callbacks,
 :_rollback_without_transaction_enrollment_callbacks=, :_before_commit_callbacks?, :aggregate_reflections,
 :_reflections=, :aggregate_reflections=, :attribute_type_decorations=, :timestamped_migrations, :attributes_to_define_after_schema_loads,
 :attributes_to_define_after_schema_loads=, :protected_environments, :connection_handler, :_reflections?,
 :aggregate_reflections?, :include_root_in_json, :include_root_in_json=, :logger=, :_validate_callbacks?, :_validators?,
 :include_root_in_json?, :local_stored_attributes, :_validate_callbacks=, :_reflections, :maintain_test_schema,
 :maintain_test_schema=, :local_stored_attributes=, :time_zone_aware_attributes, :time_zone_aware_attributes=, 
:default_timezone, :default_timezone=, :attributes_to_define_after_schema_loads?, :attribute_type_decorations?, 
:lock_optimistically, :lock_optimistically=, :warn_on_records_fetched_greater_than, :configurations, :configurations=,
 :supports_on_duplicate_key_update?, :supports_import?, :lock_optimistically?, :attribute_aliases?, :attribute_method_matchers?,
 :defined_enums=, :bulk_import, :defined_enums?, :supports_setting_primary_key_of_imported_objects?, :import_helper, 
:skip_time_zone_conversion_for_attributes, :skip_time_zone_conversion_for_attributes=, :cache_timestamp_format, 
:time_zone_aware_types, :schema_format, :schema_format=, :error_on_ignored_order_or_limit, :error_on_ignored_order_or_limit=,
 :timestamped_migrations=, :dump_schema_after_migration, :dump_schema_after_migration=, :dump_schemas, :dump_schemas=, 
:partial_writes=, :warn_on_records_fetched_greater_than=, :default_connection_handler, :connection_handler=, 
:default_connection_handler=, :time_zone_aware_types=, :skip_time_zone_conversion_for_attributes?, :time_zone_aware_types?,
 :partial_writes, :import!, :import_without_validations_or_callbacks, :import_with_validations, :partial_writes?, :bulk_import!,
 :record_timestamps, :record_timestamps=, :table_name_prefix, :after_find, :after_touch, :before_save, :around_save,
 :after_save, :before_create, :around_create, :before_update, :around_update, :after_create, :after_update, :before_destroy,
 :around_destroy, :after_destroy, :default_connection_handler?, :_validation_callbacks, :_validation_callbacks?, 
:_validation_callbacks=, :_initialize_callbacks, :_initialize_callbacks?, :_initialize_callbacks=, :_find_callbacks,
 :_find_callbacks?, :_find_callbacks=, :_touch_callbacks, :_touch_callbacks?, :_touch_callbacks=, :_save_callbacks,
 :_save_callbacks?, :_save_callbacks=, :_create_callbacks, :_create_callbacks?, :_create_callbacks=, :_update_callbacks,
 :_update_callbacks?, :_update_callbacks=, :_destroy_callbacks, :_destroy_callbacks?, :_destroy_callbacks=, :record_timestamps?,
 :belongs_to_required_by_default, :belongs_to_required_by_default=, :attribute_aliases, :attribute_aliases=, 
:attribute_method_matchers=, :attribute_method_matchers, :index_nested_attribute_errors, :index_nested_attribute_errors=, 
:import, :pluralize_table_names?, :synchronize, :logger, :_attr_readonly, :_attr_readonly=, :_attr_readonly?, 
:primary_key_prefix_type, :table_name_prefix=, :table_name_suffix=, :schema_migrations_table_name=, :internal_metadata_table_name,
 :internal_metadata_table_name=, :protected_environments=, :pluralize_table_names=, :after_initialize, :devise, :devise_modules_hook!,
 :mount_uploader, :mount_uploaders, :uploader_option, :uploader_options, :uploaders, :paginate_by_sql, :page, :paginate, :inherited,
 :per_page=, :per_page, :to_adapter, :suppress, :generate_unique_secure_token, :has_secure_token, :_store_accessors_module,
:stored_attributes, :store, :store_accessor, :reflect_on_association, :reflect_on_all_autosave_associations, :reflect_on_all_aggregations,
 :reflect_on_aggregation, :clear_reflections_cache, :_reflect_on_association, :reflections, :reflect_on_all_associations, 
:no_touching, :after_rollback, :transaction, :before_commit, :before_commit_without_transaction_enrollment, :after_create_commit,
 :after_update_commit, :after_destroy_commit, :after_commit_without_transaction_enrollment, :after_rollback_without_transaction_enrollment,
 :raise_in_transactional_callbacks, :raise_in_transactional_callbacks=, :after_commit, :composed_of, :accepts_nested_attributes_for,
 :has_secure_password, :has_and_belongs_to_many, :belongs_to, :has_many, :has_one, :after_validation, :before_validation, :serialize,
 :define_method_attribute, :primary_key, :primary_key=, :get_primary_key, :dangerous_attribute_method?, :quoted_primary_key, 
:reset_primary_key, :define_method_attribute=, :define_attribute_methods, :undefine_attribute_methods, 
:instance_method_already_implemented?, :method_defined_within?, :dangerous_class_method?, :class_method_defined_within?,
 :attribute_method?, :has_attribute?, :attribute_names, :initialize_generated_modules, :column_for_attribute,
 :attribute_method_prefix, :attribute_method_suffix, :attribute_method_affix, :generated_attribute_methods, 
:attribute_alias?, :attribute_alias, :define_attribute_method, :alias_attribute, :reset_locking_column, :update_counters,
 :locking_enabled?, :locking_column, :locking_column=, :decorate_matching_attribute_types, :decorate_attribute_type, 
:attribute, :define_attribute, :decrement_counter, :reset_counters, :increment_counter, :validates_uniqueness_of, 
:validates_absence_of, :validates_presence_of, :validates_associated, :validates_size_of, :validates_length_of, 
:validates_format_of, :validates_inclusion_of, :validates_confirmation_of, :validates_numericality_of, :validates_exclusion_of,
 :validates_acceptance_of, :set_callbacks, :skip_callback, :define_callbacks, :reset_callbacks, :deprecated_false_terminator,
 :normalize_callback_params, :__update_callbacks, :get_callbacks, :set_callback, :define_model_callbacks, :validates_each, 
:validates_with, :validators, :clear_validators!, :validators_on, :validate, :validates, :_validates_default_keys,
 :_parse_validates_options, :validates!, :to_param, :_to_partial_path, :replace_named_bind_variables, :replace_bind_variables,
 :raise_if_bind_arity_mismatch, :replace_bind_variable, :quote_bound_value, :sanitize, :sanitize_sql, :sanitize_conditions,
 :quote_value, :sanitize_sql_for_conditions, :sanitize_sql_for_assignment, :sanitize_sql_hash_for_assignment, 
:sanitize_sql_for_order, :expand_hash_conditions_for_aggregates, :sanitize_sql_array, :sanitize_sql_like, :default_extensions,
 :valid_scope_name?, :scope, :default_scoped, :scope_for_association, :all, :before_remove_const, :unscoped, 
:build_default_scope, :evaluate_default_scope, :ignore_default_scope?, :ignore_default_scope=, :default_scope, :scope_attributes?,
 :current_scope=, :scope_attributes, :current_scope, :compute_type, :new, :base_class, :abstract_class?, 
:finder_needs_type_condition?, :abstract_class, :abstract_class=, :descends_from_active_record?, :sti_name, :column_defaults,
 :content_columns, :columns, :column_names, :attribute_types, :quoted_table_name, :prefetch_primary_key?, :sequence_name,
 :_default_attributes, :table_exists?, :inheritance_column, :ignored_columns, :ignored_columns=, :inheritance_column=,
 :initialize_load_schema_monitor, :attributes_builder, :reset_table_name, :table_name=, :type_for_attribute, :reset_column_information,
 :columns_hash, :full_table_name_prefix, :table_name, :full_table_name_suffix, :reset_sequence_name, :sequence_name=,
 :next_sequence_value, :attr_readonly, :readonly_attributes, :create, :create!, :instantiate, :type_caster, :arel_table, 
:initialize_find_by_cache, :inspect, :===, :generated_association_methods, :find, :arel_engine, :arel_attribute, :predicate_builder,
 :find_by, :find_by!, :allocate, :collection_cache_key, :relation_delegate_class, :initialize_relation_delegate_cache, :enum,
 :collecting_queries_for_explain, :exec_explain, :respond_to?, :lookup_ancestors, :i18n_scope, :human_attribute_name, :having,
 :references, :distinct, :readonly, :take, :none, :or, :includes, :average, :maximum, :unscope, :sum, :uniq, :count_by_sql,
 :minimum, :find_by_sql, :count, :ids, :offset, :many?, :delete_all, :pluck, :order, :last, :destroy, :limit, :take!, :first!,
 :last!, :second!, :third!, :fourth!, :forty_two!, :third_to_last!, :fifth!, :second_to_last!, :first_or_create, :first_or_create!,
 :first_or_initialize, :find_or_create_by, :find_or_create_by!, :find_or_initialize_by, :destroy_all, :delete, :exists?, 
:update_all, :find_each, :find_in_batches, :in_batches, :except, :joins, :select, :reorder, :group, :left_joins, :left_outer_joins,
 :rewhere, :preload, :lock, :second, :where, :calculate, :from, :create_with, :first, :update, :any?, :one?, :none?, 
:fourth, :third, :forty_two, :fifth, :second_to_last, :third_to_last, :eager_load, :uncached, :cache, :clear_reloadable_connections!,
 :retrieve_connection, :connection_id=, :connection_config, :clear_active_connections!, :clear_all_connections!, :postgresql_connection,
 :remove_connection, :connection_pool, :connection_specification_name, :connection_specification_name=, :connection, 
:connection_id, :connected?, :clear_cache!, :descendants, :direct_descendants, :benchmark, :model_name, :yaml_tag,
 :class_attribute, :json_creatable?, :subclasses, :superclass, :mattr_accessor, :anonymous?, :reachable?, :parent, 
:pretty_print_cycle, :included_modules, :include?, :ancestors, :attr, :attr_reader, :attr_writer, :attr_accessor, 
:instance_methods, :public_instance_methods, :protected_instance_methods, :private_instance_methods, :constants, :const_get, 
:const_set, :const_defined?, :const_source_location, :class_variables, :remove_class_variable, :class_variable_get, 
:class_variable_set, :class_variable_defined?, :public_constant, :private_constant, :<, :deprecate_constant, :>, :singleton_class?,
 :class_eval, :module_eval, :module_exec, :include, :remove_method, :undef_method, :alias_method, :method_defined?, 
:class_exec, :public_method_defined?, :protected_method_defined?, :private_class_method, :define_method, :public_class_method,
 :private_method_defined?, :attr_internal_accessor, :attr_internal, :instance_method, :public_instance_method, :autoload, :autoload?,
 :parents, :thread_mattr_writer, :thread_cattr_writer, :remove_possible_method, :remove_possible_singleton_method, 
:thread_cattr_reader, :qualified_const_set, :alias_method_chain, :attr_internal_reader, :deprecate, :attr_internal_writer,
 :qualified_const_defined?, :thread_mattr_accessor, :thread_cattr_accessor, :thread_mattr_reader, :qualified_const_get,
 :pretty_print, :<=>, :<=, :>=, :==, :parent_name, :freeze, :local_constants, :rake_extension, :prepend, :to_s, :delegate,
:redefine_method, :name, :method_visibility, :mattr_reader, :cattr_reader, :mattr_writer, :cattr_writer, :cattr_accessor,
 :unloadable, :guess_for_anonymous, :const_missing, :concerning, :concern, :untaint, :to_json, :presence, :as_json, :acts_like?,
 :to_yaml, :instance_variable_names, :instance_values, :blank?, :present?, :__binding__, :deep_dup, :`, :duplicable?, :in?,
 :presence_in, :with_options, :html_safe?, :pry, :to_query, :pretty_print_inspect, :pretty_print_instance_variables, 
:require_dependency, :load_dependency, :require_or_load, :try, :try!, :dup, :itself, :yield_self, :then, :taint, :tainted?,
 :untrust, :untrusted?, :trust, :frozen?, :methods, :singleton_methods, :protected_methods, :private_methods, :public_methods,
 :instance_variables, :instance_variable_get, :instance_variable_set, :instance_variable_defined?, :remove_instance_variable,
 :instance_of?, :kind_of?, :is_a?, :tap, :class, :clone, :display, :hash, :singleton_class, :singleton_method, :method, :public_send,
 :define_singleton_method, :public_method, :gem, :pretty_inspect, :extend, :to_enum, :enum_for, :=~, :!~, :nil?, :eql?, :object_id, :send, :__send__, :!, :!=, :__id__, :equal?, :instance_eval, :instance_exec
